/*
 * Calculator API
 *
 * API for performing arithmetic operations and JWT-based authentication.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class CalculationResponse : IEquatable<CalculationResponse>
    { 
        /// <summary>
        /// The first number received
        /// </summary>
        /// <value>The first number received</value>

        [DataMember(Name="num1")]
        public decimal? Num1 { get; set; }

        /// <summary>
        /// The second number received
        /// </summary>
        /// <value>The second number received</value>

        [DataMember(Name="num2")]
        public decimal? Num2 { get; set; }

        /// <summary>
        /// The operation performed
        /// </summary>
        /// <value>The operation performed</value>

        [DataMember(Name="operation")]
        public string Operation { get; set; }

        /// <summary>
        /// The result of the operation
        /// </summary>
        /// <value>The result of the operation</value>

        [DataMember(Name="result")]
        public decimal? Result { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CalculationResponse {\n");
            sb.Append("  Num1: ").Append(Num1).Append("\n");
            sb.Append("  Num2: ").Append(Num2).Append("\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  Result: ").Append(Result).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((CalculationResponse)obj);
        }

        /// <summary>
        /// Returns true if CalculationResponse instances are equal
        /// </summary>
        /// <param name="other">Instance of CalculationResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CalculationResponse other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Num1 == other.Num1 ||
                    Num1 != null &&
                    Num1.Equals(other.Num1)
                ) && 
                (
                    Num2 == other.Num2 ||
                    Num2 != null &&
                    Num2.Equals(other.Num2)
                ) && 
                (
                    Operation == other.Operation ||
                    Operation != null &&
                    Operation.Equals(other.Operation)
                ) && 
                (
                    Result == other.Result ||
                    Result != null &&
                    Result.Equals(other.Result)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Num1 != null)
                    hashCode = hashCode * 59 + Num1.GetHashCode();
                    if (Num2 != null)
                    hashCode = hashCode * 59 + Num2.GetHashCode();
                    if (Operation != null)
                    hashCode = hashCode * 59 + Operation.GetHashCode();
                    if (Result != null)
                    hashCode = hashCode * 59 + Result.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(CalculationResponse left, CalculationResponse right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(CalculationResponse left, CalculationResponse right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
